"""
models/alert.py
---------------
ORM model for system alerts.

Alerts are auto-generated by backend logic when hotspots cross thresholds,
or when critical events are ingested. They appear on the Overview dashboard.
"""

from sqlalchemy import Column, String, Boolean, DateTime, Text
from datetime import datetime, timezone
import uuid

from app.database import Base


class SystemAlert(Base):
    __tablename__ = "system_alerts"

    id = Column(String(40), primary_key=True, default=lambda: str(uuid.uuid4()))
    severity = Column(String(20), nullable=False)      # critical | high | medium | low
    message = Column(Text, nullable=False)             # Human-readable alert description
    source = Column(String(50), nullable=True)         # Bus ID or hotspot reference
    details = Column(Text, nullable=True)              # Location or additional context
    timestamp = Column(DateTime, default=lambda: datetime.now(timezone.utc))
    acknowledged = Column(Boolean, default=False)
