DEFAULT_MODEL = "yolov8n.pt"
CONFIDENCE_THRESHOLD = 0.25
DISTANCE_THRESHOLD = 60  # Pixels for clustering
EVENT_EMIT_INTERVAL_SEC = 1.0  # Minimum time between logs
GPS_DISTANCE_THRESHOLD = 0.0001  # Minimum coordinate change to log again if stopped
HEALING_DISTANCE_RADIUS_METERS = 15
HEALING_FRAME_CONFIDENCE = 15
DEDUPLICATION_RADIUS_METERS = 2.0
